included: # 执行 linting 时包含的路径。如果出现这个 `--path` 会被忽略。
  - RICHSDK
excluded: # 执行 linting 时忽略的路径。 优先级比 `included` 更高。
  - RICHSDK/Kit/FoundationExtension.swift
  - Pods
# 分析规则
analyzer_rules:
  - unused_declaration
  - unused_import
# 启用以下规则
opt_in_rules:
  - anyobject_protocol
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - test_case_accessibility
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition
# 标识符
identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - i
    - key
    - iv
    - x
    - y
    - vc
    - id
    - GlobalAPIKey
number_separator:
  minimum_length: 5
# 二进制规则可以设置他们的严格程度
force_cast: warning # 隐式
force_try:
  severity: warning # 显式
line_length: 150
# 文件行数
file_length:
  warning: 800
  error: 1200
# 不会运行的规则
disabled_rules:
  - function_body_length
  - unused_optional_binding
  - multiple_closures_with_trailing_closure
  - cyclomatic_complexity
# 报告类型 (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"
